// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using matcher;

namespace matcher.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20191123013218_userpreferences")]
    partial class userpreferences
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.1");

            modelBuilder.Entity("matcher.Room", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("game")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("time")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("matcher.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("name")
                        .HasColumnType("TEXT");

                    b.Property<string>("password")
                        .HasColumnType("TEXT");

                    b.Property<string>("roomId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("roomId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("matcher.UserPreference", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("game")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("time")
                        .HasColumnType("TEXT");

                    b.Property<string>("userId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("userId");

                    b.ToTable("UserPreferences");
                });

            modelBuilder.Entity("matcher.User", b =>
                {
                    b.HasOne("matcher.Room", "room")
                        .WithMany("users")
                        .HasForeignKey("roomId");
                });

            modelBuilder.Entity("matcher.UserPreference", b =>
                {
                    b.HasOne("matcher.User", "user")
                        .WithMany("preferences")
                        .HasForeignKey("userId");
                });
#pragma warning restore 612, 618
        }
    }
}
